version: "3"

services:
  app:
    build: app
    ports:
      - "5000"
  
  nginx:
    image: nginx:stable-alpine3.17-slim
    RUN: rm /etc/nginx/conf.d/default.conf
    COPY nginx.conf /etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "80:80"
      
